<?xml version="1.0" encoding="UTF8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.eouna</groupId>
    <artifactId>ConfigTool</artifactId>
    <version>1.0.5</version>
    <packaging>pom</packaging>
    <name>ConfigTool</name>

    <modules>
        <module>eouna-core</module>
        <module>configtool-app</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF8</project.build.sourceEncoding>
        <junit.version>5.9.2</junit.version>
        <java.version>17</java.version>
        <openjfx.version>17.0.2</openjfx.version>
        <poi.version>5.4.0</poi.version>
        <aspectj.version>1.9.24</aspectj.version>
        <lombok.version>1.18.36</lombok.version>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <!--编译插件-->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.10.1</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <!--启用 Lombok 注解处理器-->
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>